# Generated by Django 2.2 on 2019-04-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=16)),
                ('user_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=32)),
                ('helpfulness', models.CharField(max_length=8)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('summary', models.CharField(max_length=256)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Food Review',
                'verbose_name_plural': 'Food Reviews',
            },
        ),
    ]
